import bcrypt from "bcryptjs";
import type { StoreData } from "./types";

/** Precomputed bcrypt hashes for the seeded passwords (cost 10). */
const HASHES = {
  password123: bcrypt.hashSync("password123", 10),
  admin123: bcrypt.hashSync("admin123", 10),
};

export function createSeedData(): StoreData {
  return {
    users: [
      {
        id: "user-standard",
        username: "standard",
        displayName: "Standard User",
        passwordHash: HASHES.password123,
        role: "user",
        locked: false,
      },
      {
        id: "user-admin",
        username: "admin",
        displayName: "Admin User",
        passwordHash: HASHES.admin123,
        role: "admin",
        locked: false,
      },
      {
        id: "user-locked",
        username: "locked",
        displayName: "Locked User",
        passwordHash: HASHES.password123,
        role: "user",
        locked: true,
      },
    ],
    products: [
      {
        id: "prod-1",
        sku: "SR-USB-C",
        name: "USB-C Dock Hub",
        description: "7-port USB-C hub with HDMI and PD passthrough for desk setups.",
        category: "Electronics",
        price: 49.99,
        stock: 42,
        imageHue: 200,
      },
      {
        id: "prod-2",
        sku: "SR-NB-A5",
        name: "Field Notebook A5",
        description: "Waterproof field notebook with numbered pages and tear-out sheets.",
        category: "Stationery",
        price: 12.5,
        stock: 120,
        imageHue: 35,
      },
      {
        id: "prod-3",
        sku: "SR-HDR-L",
        name: "Warehouse Hard Hat",
        description: "Vented ABS hard hat with adjustable ratchet suspension.",
        category: "Safety",
        price: 28.0,
        stock: 64,
        imageHue: 48,
      },
      {
        id: "prod-4",
        sku: "SR-GLV-M",
        name: "Grip Work Gloves",
        description: "Cut-resistant gloves with coated palms for packing lines.",
        category: "Safety",
        price: 15.75,
        stock: 200,
        imageHue: 150,
      },
      {
        id: "prod-5",
        sku: "SR-LBL-R",
        name: "Thermal Label Roll",
        description: "1000-count 4×6 thermal shipping labels for barcode printers.",
        category: "Packaging",
        price: 22.0,
        stock: 85,
        imageHue: 280,
      },
      {
        id: "prod-6",
        sku: "SR-TAP-C",
        name: "Carton Sealing Tape",
        description: "Heavy-duty clear packing tape, 48mm × 100m, pack of 6.",
        category: "Packaging",
        price: 18.4,
        stock: 150,
        imageHue: 190,
      },
      {
        id: "prod-7",
        sku: "SR-SCN-1",
        name: "Handheld Barcode Scanner",
        description: "2D imager scanner with USB cradle for receiving desks.",
        category: "Electronics",
        price: 129.0,
        stock: 18,
        imageHue: 220,
      },
      {
        id: "prod-8",
        sku: "SR-BIN-S",
        name: "Stackable Parts Bin",
        description: "Modular polypropylene bin for small parts shelving.",
        category: "Storage",
        price: 9.95,
        stock: 300,
        imageHue: 12,
      },
      {
        id: "prod-9",
        sku: "SR-LED-W",
        name: "LED Work Light",
        description: "Rechargeable magnetic LED lamp for aisle inspections.",
        category: "Electronics",
        price: 34.5,
        stock: 0,
        imageHue: 55,
      },
      {
        id: "prod-10",
        sku: "SR-CLIP-B",
        name: "Clipboard Bundle",
        description: "Set of 5 aluminium clipboards for cycle counts.",
        category: "Stationery",
        price: 24.0,
        stock: 55,
        imageHue: 95,
      },
    ],
    carts: {},
    orders: [],
  };
}
